
export const txt = "text-alive-txt dark:text-alive-txtd"
export const input = "text-alive-input dark:text-alive-inputd"
export const txtHover = "hover:text-alive-txth dark:hover:text-alive-txthd"
export const bg = "bg-alive-bg dark:bg-alive-bgd"
export const bgActive = "bg-alive-active dark:bg-blue-actived"
export const bgInactive = "bg-alive-inactive dark:bg-alive-inactived"
export const border = "border-alive-txt dark:border-alive-txtd"
export const alphaIcon = "w-5 h-5 ml-2 justify-self-end self-center text-alive-alpha"
export const alphaTxt = "invisible group-hover/build-info:visible w-44 absolute left-5 top-5 px-4 py-2 rounded-lg border-2 shadow-md border-alive-alpha bg-alive-bg text-alive-alpha"
export const betaIcon = "w-5 h-5 ml-2 justify-self-end self-center text-alive-beta"
export const betaTxt = "invisible group-hover/build-info:visible w-44 absolute left-5 top-5 px-4 py-2 rounded-lg border-2 shadow-md border-alive-beta bg-alive-bg text-alive-beta"
